### PR TITLE
Add whitelist feature to the buff module

### PR DESCRIPTION
**Pull request by excorp**
This was requested in the comments on the add-on homepage:

https://www.curseforge.com/wow/addons/raid-frame-settings/comments

georbig #6299484 

could I set some key buffs which not from me shows up on the buff frame ?

image
image

### CODE REVIEW

**Comment by excorp** [comment]
If you don't mind, I'd like to merge this into the #10 PR and move it up there.

**Comment by Slothpala** [comment]
No, please wait with that. There are still some minor issues with #10 that need to be resolved first. And I want to merge it into the master soon, so no more changes there if possible.

**Comment by excorp** [comment]
Yes, I get it. I will not modify except bug fix over there.

**Comment by Slothpala** [comment]
No i don't want to add that.

**Comment by excorp** [comment]
Sorry to hear that. 
There are certain buffs that the Blizzard default frame ignores by default.
Things like Grove Tending and Spring Blossoms are ignored.
You could have registered these skills using the whitelist to make them visible, but you said you didn't want them.

**Pull request closed without merging**
